services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  frontend:
    build:
      context: ./frontend_react_app
      dockerfile: Dockerfile
    volumes:
      - ./frontend_react_app:/usr/src/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    command: npm start
    environment:
      - EXPO_DEVTOOLS_LISTEN_PORT=19002

volumes:
  db_data:
