# Generated by Django 5.1.2 on 2024-10-17 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Active'), ('very_active', 'Very active')], max_length=20)),
                ('neck_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shoulder_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arm_left_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arm_right_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forearm_left_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forearm_right_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_hip_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh_left_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh_left_lower_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh_right_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thigh_right_lower_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calf_left_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calf_right_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
