# Generated by Django 5.1.2 on 2024-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_module', '0003_workoutsession_workouthistory_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
