# Generated by Django 5.1.2 on 2024-10-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_module', '0004_personalinfo_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='age',
        ),
    ]
